FileCreateDir, %A_AppData%\Plunge
FileCreateDir, %A_AppData%\Plunge\client
FileCreateDir, %A_AppData%\Plunge\graph
FileCreateDir, %A_AppData%\Plunge\res
FileCreateDir, %A_AppData%\Plunge\screens
FileCreateDir, %A_AppData%\Plunge\settings
FileCreateDir, %A_AppData%\Plunge\client\jsonrpc
FileCreateDir, %A_AppData%\Plunge\client\nubot
FileCreateDir, %A_AppData%\Plunge\client\tools
FileCreateDir, %A_AppData%\Plunge\client\nubot\res
FileCreateDir, %A_AppData%\Plunge\client\nubot\logs\NuBot_1425937391119_ccedk_NBTBTC
FileCreateDir, %A_AppData%\Plunge\client\nubot\logs\NuBot_1425938328021_ccedk_NBTBTC
FileCreateDir, %A_AppData%\Plunge\client\nubot\logs\NuBot_1425938868478_ccedk_NBTBTC
FileCreateDir, %A_AppData%\Plunge\client\nubot\logs\NuBot_1425938868845_bitcoincoid_NBTBTC
FileCreateDir, %A_AppData%\Plunge\client\nubot\logs\NuBot_1425938890709_ccedk_NBTBTC
FileCreateDir, %A_AppData%\Plunge\client\nubot\logs\NuBot_1425938891080_bitcoincoid_NBTBTC
FileCreateDir, %A_AppData%\Plunge\client\nubot\logs\NuBot_1425938892873_poloniex_NBTBTC
FileCreateDir, %A_AppData%\Plunge\client\nubot\logs\NuBot_1428415924562_poloniex_NBTBTC
FileCreateDir, %A_AppData%\Plunge\client\nubot\logs\NuBot_1428415924582_bitcoincoid_NBTBTC
FileCreateDir, %A_AppData%\Plunge\client\nubot\logs\NuBot_1428415924587_ccedk_NBTBTC
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\frozen
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\logs_assets
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\sources
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\ssl
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\logs_assets\css
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\logs_assets\img
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\logs_assets\js
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\sources\lib
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\sources\src
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\sources\lib\CopyLibs
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\sources\src\com
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\exchanges
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\global
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\launch
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\models
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\NTP
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\options
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\RPC
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\tasks
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\tests
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\trading
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\utils
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\messages
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\tasks\strategy
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\keys
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\wrappers
FileCreateDir, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\utils\logging
FileCreateDir, %A_AppData%\Plunge\res\fonts
FileCreateDir, %A_AppData%\Plunge\res\icons
FileCreateDir, %A_AppData%\Plunge\res\images
FileCreateDir, %A_AppData%\Plunge\res\json
FileCreateDir, %A_AppData%\Plunge\res\images\branding
FileCreateDir, %A_AppData%\Plunge\res\json\languages
