FileInstall, C:\Users\sammoth\Documents\projects\plunge\LICENSE, %A_AppData%\Plunge\LICENSE, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\overrides.py, %A_AppData%\Plunge\overrides.py, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\plunge.kv, %A_AppData%\Plunge\plunge.kv, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\plunge.py, %A_AppData%\Plunge\plunge.py, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\README.md, %A_AppData%\Plunge\README.md, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\setup.py, %A_AppData%\Plunge\setup.py, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\socketlogger.py, %A_AppData%\Plunge\socketlogger.py, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\utils.py, %A_AppData%\Plunge\utils.py, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\client.py, %A_AppData%\Plunge\client\client.py, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\crypto.py, %A_AppData%\Plunge\client\crypto.py, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\exchanges.py, %A_AppData%\Plunge\client\exchanges.py, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\trading.py, %A_AppData%\Plunge\client\trading.py, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\utils.py, %A_AppData%\Plunge\client\utils.py, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\__init__.py, %A_AppData%\Plunge\client\__init__.py, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\jsonrpc\cgiwrapper.py, %A_AppData%\Plunge\client\jsonrpc\cgiwrapper.py, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\jsonrpc\json.py, %A_AppData%\Plunge\client\jsonrpc\json.py, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\jsonrpc\modpywrapper.py, %A_AppData%\Plunge\client\jsonrpc\modpywrapper.py, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\jsonrpc\proxy.py, %A_AppData%\Plunge\client\jsonrpc\proxy.py, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\jsonrpc\serviceHandler.py, %A_AppData%\Plunge\client\jsonrpc\serviceHandler.py, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\jsonrpc\__init__.py, %A_AppData%\Plunge\client\jsonrpc\__init__.py, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\NuBot.jar, %A_AppData%\Plunge\client\nubot\NuBot.jar, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\currencies.csv, %A_AppData%\Plunge\client\nubot\res\currencies.csv, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\frozen\nbt_btc-bitcoincoid-frozen.json, %A_AppData%\Plunge\client\nubot\res\frozen\nbt_btc-bitcoincoid-frozen.json, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\frozen\nbt_btc-ccedk-frozen.json, %A_AppData%\Plunge\client\nubot\res\frozen\nbt_btc-ccedk-frozen.json, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\frozen\nbt_btc-poloniex-frozen.json, %A_AppData%\Plunge\client\nubot\res\frozen\nbt_btc-poloniex-frozen.json, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\frozen\nbt_usd-ccedk-frozen.json, %A_AppData%\Plunge\client\nubot\res\frozen\nbt_usd-ccedk-frozen.json, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\LICENSE.md, %A_AppData%\Plunge\client\nubot\res\sources\LICENSE.md, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\lib\commons-codec-1.7.jar, %A_AppData%\Plunge\client\nubot\res\sources\lib\commons-codec-1.7.jar, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\lib\commons-io-2.4.jar, %A_AppData%\Plunge\client\nubot\res\sources\lib\commons-io-2.4.jar, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\lib\commons-logging-1.1.3.jar, %A_AppData%\Plunge\client\nubot\res\sources\lib\commons-logging-1.1.3.jar, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\lib\commons-net-3.3.jar, %A_AppData%\Plunge\client\nubot\res\sources\lib\commons-net-3.3.jar, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\lib\fastjson-1.1.36.jar, %A_AppData%\Plunge\client\nubot\res\sources\lib\fastjson-1.1.36.jar, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\lib\gson-2.2.3.jar, %A_AppData%\Plunge\client\nubot\res\sources\lib\gson-2.2.3.jar, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\lib\httpclient-4.3.4.jar, %A_AppData%\Plunge\client\nubot\res\sources\lib\httpclient-4.3.4.jar, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\lib\httpcore-4.3.2.jar, %A_AppData%\Plunge\client\nubot\res\sources\lib\httpcore-4.3.2.jar, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\lib\jackson-core-asl-1.9.5.jar, %A_AppData%\Plunge\client\nubot\res\sources\lib\jackson-core-asl-1.9.5.jar, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\lib\jackson-mapper-asl-1.9.5.jar, %A_AppData%\Plunge\client\nubot\res\sources\lib\jackson-mapper-asl-1.9.5.jar, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\lib\java-mail-1.4.4.jar, %A_AppData%\Plunge\client\nubot\res\sources\lib\java-mail-1.4.4.jar, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\lib\json-simple-1.1.1.jar, %A_AppData%\Plunge\client\nubot\res\sources\lib\json-simple-1.1.1.jar, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\lib\jsoup-1.7.3.jar, %A_AppData%\Plunge\client\nubot\res\sources\lib\jsoup-1.7.3.jar, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\lib\junit-4.12.jar, %A_AppData%\Plunge\client\nubot\res\sources\lib\junit-4.12.jar, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\lib\mailapi-1.4.4.jar, %A_AppData%\Plunge\client\nubot\res\sources\lib\mailapi-1.4.4.jar, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\lib\nblibraries.properties, %A_AppData%\Plunge\client\nubot\res\sources\lib\nblibraries.properties, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\lib\org.json-20120521.jar, %A_AppData%\Plunge\client\nubot\res\sources\lib\org.json-20120521.jar, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\lib\smtp-1.4.4.jar, %A_AppData%\Plunge\client\nubot\res\sources\lib\smtp-1.4.4.jar, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\lib\CopyLibs\org-netbeans-modules-java-j2seproject-copylibstask.jar, %A_AppData%\Plunge\client\nubot\res\sources\lib\CopyLibs\org-netbeans-modules-java-j2seproject-copylibstask.jar, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\settings.properties, %A_AppData%\Plunge\client\nubot\res\sources\src\settings.properties, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\exchanges\Exchange.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\exchanges\Exchange.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\exchanges\ExchangeLiveData.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\exchanges\ExchangeLiveData.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\exchanges\ExchangeStatus.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\exchanges\ExchangeStatus.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\global\Constant.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\global\Constant.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\global\Global.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\global\Global.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\global\PasswordsSample.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\global\PasswordsSample.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\launch\NuBot.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\launch\NuBot.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\launch\NuCancelOrders.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\launch\NuCancelOrders.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\launch\NuExecuteOrders.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\launch\NuExecuteOrders.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\launch\NuLastTrades.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\launch\NuLastTrades.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\launch\NuPriceMonitor.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\launch\NuPriceMonitor.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\models\Amount.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\models\Amount.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\models\ApiError.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\models\ApiError.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\models\ApiResponse.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\models\ApiResponse.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\models\Balance.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\models\Balance.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\models\Currency.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\models\Currency.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\models\CurrencyPair.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\models\CurrencyPair.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\models\LastPrice.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\models\LastPrice.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\models\Order.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\models\Order.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\models\Trade.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\models\Trade.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\HipChatNotifications.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\HipChatNotifications.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\MailNotifications.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\MailNotifications.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\HipChat.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\HipChat.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\HipChatConstants.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\HipChatConstants.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\Room.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\Room.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\RoomId.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\RoomId.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\RoomParser.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\RoomParser.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\User.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\User.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\UserId.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\UserId.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\UserParser.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\UserParser.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\UtilParser.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\UtilParser.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\messages\BaseMessage.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\messages\BaseMessage.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\messages\HistoryMessage.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\messages\HistoryMessage.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\messages\Message.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\messages\Message.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\messages\MessageParser.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\messages\MessageParser.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\messages\UploadReference.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\notifications\jhipchat\messages\UploadReference.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\NTP\NTPClient.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\NTP\NTPClient.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\options\OptionsJSON.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\options\OptionsJSON.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\options\SecondaryPegOptionsJSON.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\options\SecondaryPegOptionsJSON.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\AbstractPriceFeed.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\AbstractPriceFeed.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\BitcoinaveragePriceFeed.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\BitcoinaveragePriceFeed.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\BitfinexPriceFeed.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\BitfinexPriceFeed.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\BitstampEURPriceFeed.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\BitstampEURPriceFeed.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\BitstampPriceFeed.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\BitstampPriceFeed.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\BlockchainPriceFeed.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\BlockchainPriceFeed.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\BtcePriceFeed.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\BtcePriceFeed.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\BterPriceFeed.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\BterPriceFeed.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\CcedkPriceFeed.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\CcedkPriceFeed.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\CoinbasePriceFeed.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\CoinbasePriceFeed.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\CoinmarketcapnexuistPriceFeed.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\CoinmarketcapnexuistPriceFeed.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\CoinmarketcapnorthpolePriceFeed.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\CoinmarketcapnorthpolePriceFeed.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\ExchangeratelabPriceFeed.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\ExchangeratelabPriceFeed.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\GoogleUnofficialPriceFeed.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\GoogleUnofficialPriceFeed.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\OpenexchangeratesPriceFeed.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\OpenexchangeratesPriceFeed.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\PriceFeedManager.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\PriceFeedManager.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\YahooPriceFeed.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\pricefeeds\YahooPriceFeed.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\RPC\NuRPCClient.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\RPC\NuRPCClient.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\tasks\BotTask.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\tasks\BotTask.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\tasks\CheckConnectionTask.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\tasks\CheckConnectionTask.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\tasks\CheckNudTask.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\tasks\CheckNudTask.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\tasks\NuPriceMonitorTask.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\tasks\NuPriceMonitorTask.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\tasks\SubmitLiquidityinfoTask.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\tasks\SubmitLiquidityinfoTask.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\tasks\TaskManager.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\tasks\TaskManager.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\tasks\strategy\PriceMonitorTriggerTask.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\tasks\strategy\PriceMonitorTriggerTask.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\tasks\strategy\StrategyPrimaryPegTask.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\tasks\strategy\StrategyPrimaryPegTask.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\tasks\strategy\StrategySecondaryPegTask.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\tasks\strategy\StrategySecondaryPegTask.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\tasks\strategy\StrategySecondaryPegUtils.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\tasks\strategy\StrategySecondaryPegUtils.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\tests\ExecuteWrapperTests.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\tests\ExecuteWrapperTests.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\tests\TestAggregateOptions.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\tests\TestAggregateOptions.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\tests\TestFroozenAmounts.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\tests\TestFroozenAmounts.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\tests\TestNotifications.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\tests\TestNotifications.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\tests\TestNTPClient.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\tests\TestNTPClient.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\tests\TestOrderTask.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\tests\TestOrderTask.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\tests\TestPriceFeed.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\tests\TestPriceFeed.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\tests\TestQuick.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\tests\TestQuick.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\tests\TestReadCsv.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\tests\TestReadCsv.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\tests\TestRPC.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\tests\TestRPC.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\tests\TestSync.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\tests\TestSync.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\tests\TestWrapperReturns.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\tests\TestWrapperReturns.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\tests\TestWrappers.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\tests\TestWrappers.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\ServiceInterface.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\ServiceInterface.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\Ticker.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\Ticker.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\TradeInterface.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\TradeInterface.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\TradeUtils.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\TradeUtils.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\keys\ApiKeys.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\keys\ApiKeys.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\keys\ApiPermissions.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\keys\ApiPermissions.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\wrappers\AllCoinWrapper.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\wrappers\AllCoinWrapper.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\wrappers\BitcoinCoIDWrapper.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\wrappers\BitcoinCoIDWrapper.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\wrappers\BitSparkWrapper.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\wrappers\BitSparkWrapper.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\wrappers\BtceWrapper.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\wrappers\BtceWrapper.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\wrappers\BterWrapper.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\wrappers\BterWrapper.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\wrappers\CcedkWrapper.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\wrappers\CcedkWrapper.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\wrappers\CcexWrapper.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\wrappers\CcexWrapper.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\wrappers\ExcoinWrapper.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\wrappers\ExcoinWrapper.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\wrappers\PeatioWrapper.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\wrappers\PeatioWrapper.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\wrappers\PoloniexWrapper.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\trading\wrappers\PoloniexWrapper.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\utils\ErrorManager.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\utils\ErrorManager.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\utils\FileSystem.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\utils\FileSystem.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\utils\FrozenBalancesManager.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\utils\FrozenBalancesManager.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\utils\HttpUtils.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\utils\HttpUtils.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\utils\Utils.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\utils\Utils.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\utils\logging\LogFormatterCSV.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\utils\logging\LogFormatterCSV.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\utils\logging\LogFormatterHTML.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\utils\logging\LogFormatterHTML.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\sources\src\com\nubits\nubot\utils\logging\NuLogger.java, %A_AppData%\Plunge\client\nubot\res\sources\src\com\nubits\nubot\utils\logging\NuLogger.java, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\ssl\nubot_keystore.jks, %A_AppData%\Plunge\client\nubot\res\ssl\nubot_keystore.jks, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\ssl\nubot_keystore_old.jks, %A_AppData%\Plunge\client\nubot\res\ssl\nubot_keystore_old.jks, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\nubot\res\ssl\updateKeystore.sh, %A_AppData%\Plunge\client\nubot\res\ssl\updateKeystore.sh, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\client\tools\pay.py, %A_AppData%\Plunge\client\tools\pay.py, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\graph\LICENSE, %A_AppData%\Plunge\graph\LICENSE, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\graph\README.md, %A_AppData%\Plunge\graph\README.md, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\graph\screenshot.png, %A_AppData%\Plunge\graph\screenshot.png, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\graph\__init__.py, %A_AppData%\Plunge\graph\__init__.py, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\res\fonts\LICENSE.txt, %A_AppData%\Plunge\res\fonts\LICENSE.txt, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\res\fonts\Roboto-Black.ttf, %A_AppData%\Plunge\res\fonts\Roboto-Black.ttf, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\res\fonts\Roboto-BlackItalic.ttf, %A_AppData%\Plunge\res\fonts\Roboto-BlackItalic.ttf, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\res\fonts\Roboto-Bold.ttf, %A_AppData%\Plunge\res\fonts\Roboto-Bold.ttf, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\res\fonts\Roboto-BoldItalic.ttf, %A_AppData%\Plunge\res\fonts\Roboto-BoldItalic.ttf, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\res\fonts\Roboto-Italic.ttf, %A_AppData%\Plunge\res\fonts\Roboto-Italic.ttf, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\res\fonts\Roboto-Light.ttf, %A_AppData%\Plunge\res\fonts\Roboto-Light.ttf, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\res\fonts\Roboto-LightItalic.ttf, %A_AppData%\Plunge\res\fonts\Roboto-LightItalic.ttf, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\res\fonts\Roboto-Medium.ttf, %A_AppData%\Plunge\res\fonts\Roboto-Medium.ttf, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\res\fonts\Roboto-MediumItalic.ttf, %A_AppData%\Plunge\res\fonts\Roboto-MediumItalic.ttf, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\res\fonts\Roboto-Regular.ttf, %A_AppData%\Plunge\res\fonts\Roboto-Regular.ttf, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\res\fonts\Roboto-Thin.ttf, %A_AppData%\Plunge\res\fonts\Roboto-Thin.ttf, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\res\fonts\Roboto-ThinItalic.ttf, %A_AppData%\Plunge\res\fonts\Roboto-ThinItalic.ttf, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\res\icons\nu.ico, %A_AppData%\Plunge\res\icons\nu.ico, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\res\icons\nu.png, %A_AppData%\Plunge\res\icons\nu.png, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\res\icons\nubits.png, %A_AppData%\Plunge\res\icons\nubits.png, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\res\icons\nushares.png, %A_AppData%\Plunge\res\icons\nushares.png, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\res\images\branding\black.png, %A_AppData%\Plunge\res\images\branding\black.png, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\res\images\branding\blue.png, %A_AppData%\Plunge\res\images\branding\blue.png, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\res\images\branding\red.png, %A_AppData%\Plunge\res\images\branding\red.png, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\res\images\branding\yellow.png, %A_AppData%\Plunge\res\images\branding\yellow.png, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\res\json\languages\english.json, %A_AppData%\Plunge\res\json\languages\english.json, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\screens\HomeScreen.kv, %A_AppData%\Plunge\screens\HomeScreen.kv, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\screens\HomeScreen.py, %A_AppData%\Plunge\screens\HomeScreen.py, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\screens\__init__.py, %A_AppData%\Plunge\screens\__init__.py, 1
FileInstall, C:\Users\sammoth\Documents\projects\plunge\settings\plunge.json, %A_AppData%\Plunge\settings\plunge.json, 1
